In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv('job_hunting.csv', encoding="shift-jis" )

In [11]:
df_train = df.iloc[:,1:11]
df_train.head()

Jul-17  Aug-17  Sep-17  Oct-17  Nov-17  Dec-17  Jan-18  Feb-18  Mar-18  \
0   40500   33100   27100   22200   22200   22200   27100   27100   27100   
1    5400    4400    5400    5400    5400    5400    6600    8100    6600   
2   49500   33100   33100   33100   33100   33100   40500   60500   90500   
3   74000   74000   60500   40500   40500   40500   49500   49500   33100   
4    5400    4400    4400    5400    6600    8100   14800   18100   18100   

   Apr-18  
0   33100  
1    6600  
2   60500  
3   60500  
4    6600

In [14]:
df_array = df_train.values
df_array

array([[40500, 33100, 27100, ..., 27100, 27100, 33100],
       [ 5400,  4400,  5400, ...,  8100,  6600,  6600],
       [49500, 33100, 33100, ..., 60500, 90500, 60500],
       ...,
       [   10,    10,     0, ...,     0,    10,     0],
       [    0,     0,    10, ...,    10,    10,     0],
       [    0,    10,     0, ...,    10,     0,     0]], dtype=int64)

In [15]:
import numpy as np
def normalize(v, axis=-1, order=2):
    l2 = np.linalg.norm(v, ord = order, axis=axis, keepdims=True)
    l2[l2==0] = 1
    return v/l2

In [18]:
df_train_normalize = normalize(df_array, axis = 1)
# df_train1 = pd.DataFrame(df_train_normalize)
# df_train1.head()

In [19]:
df_train_normalize

array([[0.44595438, 0.36447136, 0.29840405, ..., 0.29840405, 0.29840405,
        0.36447136],
       [0.28403355, 0.23143475, 0.28403355, ..., 0.42605033, 0.34715212,
        0.34715212],
       [0.31257014, 0.20901155, 0.20901155, ..., 0.38203018, 0.57146663,
        0.38203018],
       ...,
       [0.57735027, 0.57735027, 0.        , ..., 0.        , 0.57735027,
        0.        ],
       [0.        , 0.        , 0.40824829, ..., 0.40824829, 0.40824829,
        0.        ],
       [0.        , 0.70710678, 0.        , ..., 0.70710678, 0.        ,
        0.        ]])

In [24]:
df = pd.DataFrame(df_train_normalize,  columns=['Jul-17', 'Aug-17', 'Sep-17', 'Nov-17', 'Dec-17', 'Jan-18', 'Feb-18', 'Mar-18', 'Apr-18', 'Jun-18'])
df.head()

Jul-17    Aug-17    Sep-17    Nov-17    Dec-17    Jan-18    Feb-18  \
0  0.445954  0.364471  0.298404  0.244449  0.244449  0.244449  0.298404   
1  0.284034  0.231435  0.284034  0.284034  0.284034  0.284034  0.347152   
2  0.312570  0.209012  0.209012  0.209012  0.209012  0.209012  0.255739   
3  0.433131  0.433131  0.354114  0.237052  0.237052  0.237052  0.289730   
4  0.161066  0.131239  0.131239  0.161066  0.196859  0.241600  0.441441   

     Mar-18    Apr-18    Jun-18  
0  0.298404  0.298404  0.364471  
1  0.426050  0.347152  0.347152  
2  0.382030  0.571467  0.382030  
3  0.289730  0.193738  0.354114  
4  0.539871  0.539871  0.196859

In [25]:
from sklearn.cluster import k_means

n_cluster = 4
centroid, label, inertia = k_means(df, n_cluster, random_state = 0)
centroid, label, inertia

(array([[0.11958764, 0.12183297, 0.12464057, 0.13112138, 0.13616043,
         0.1596576 , 0.27382795, 0.74144276, 0.28693713, 0.15649722],
        [0.30536452, 0.27715058, 0.28417665, 0.29578662, 0.2788485 ,
         0.27238029, 0.33676121, 0.31184996, 0.31961762, 0.31924463],
        [0.48882645, 0.3461311 , 0.28399022, 0.25298497, 0.19811897,
         0.17505972, 0.17456444, 0.13779736, 0.11341352, 0.13001808],
        [0.24160413, 0.16781161, 0.15577849, 0.13405713, 0.14164154,
         0.13692098, 0.20821259, 0.23481093, 0.43118297, 0.60228664]]),
 array([1, 1, 1, ..., 2, 1, 0]),
 172.06463361956483)

In [26]:
# ラベル0を取り出す
df0 = df[label == 0]
df0_mean = df0.mean()
df0_mean

Jul-17    0.119588
Aug-17    0.121833
Sep-17    0.124641
Nov-17    0.131121
Dec-17    0.136160
Jan-18    0.159658
Feb-18    0.273828
Mar-18    0.741443
Apr-18    0.286937
Jun-18    0.156497
dtype: float64

In [27]:
# ラベル1を取り出す
df1 = df[label == 1]
df1_mean = df1.mean()
df1_mean

Jul-17    0.305365
Aug-17    0.277151
Sep-17    0.284177
Nov-17    0.295787
Dec-17    0.278849
Jan-18    0.272380
Feb-18    0.336761
Mar-18    0.311850
Apr-18    0.319618
Jun-18    0.319245
dtype: float64

In [28]:
# ラベル2を取り出す
df2 = df[label == 2]
df2_mean = df2.mean()
df2_mean

Jul-17    0.488826
Aug-17    0.346131
Sep-17    0.283990
Nov-17    0.252985
Dec-17    0.198119
Jan-18    0.175060
Feb-18    0.174564
Mar-18    0.137797
Apr-18    0.113414
Jun-18    0.130018
dtype: float64

In [29]:
# ラベル3を取り出す
df3 = df[label == 3]
df3_mean = df3.mean()
df3_mean

Jul-17    0.241604
Aug-17    0.167812
Sep-17    0.155778
Nov-17    0.134057
Dec-17    0.141642
Jan-18    0.136921
Feb-18    0.208213
Mar-18    0.234811
Apr-18    0.431183
Jun-18    0.602287
dtype: float64